namespace: "vertica"
# Metadata for the VerticaDB
verticaDB:
  metadata:
    name: verticadb # Name of the VerticaDB instance

  # Define subclusters for the VerticaDB
  subclusters:
    - name: sc1 # Name of the first subcluster
      size: 3 # Number of instances in this subcluster
      serviceType: NodePort # Service type for the subcluster
      resources:
        limits:
          cpu: "2" # CPU limit for the subcluster
          memory: "2Gi" # Memory limit for the subcluster
        requests:
          cpu: "1" # CPU request for the subcluster
          memory: "1Gi" # Memory request for the subcluster

  # Image information for the VerticaDB
  image:
    repository: opentext/vertica-k8s # Docker image repository for Vertica
    tag: latest # Image tag/version

  # Local storage information for the VerticaDB
  local:
    requestSize: "20Gi" # Amount of local storage to request

  # Communal storage information for the VerticaDB
  communal:
    path: "/home/test/vertica/vertica6" # Path to communal storage

  # Volume mounts for the communal storage
  volumeMounts:
    communalStorageMountPath: "/home/test/vertica/vertica6" # Mount path for communal storage

  # Volumes definition for the PersistentVolumeClaim
  volumes:
    pvcClaimName: verticadb-pvc # PersistentVolumeClaim name



persistentVolume:
  name: verticadb-pv
  storageClassName: longhorn
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/test/vertica/vertica6"
  nodeAffinity:
    operator: In  # Could be "In", "NotIn", etc.
    values:
      - k8s-node2


persistentVolumeClaim:
  name: verticadb-pvc
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi


verticaBackup:
  cronJob:
    enabled: true
    name: vertica-backup
    schedule: "*/5 * * * *"  # Schedule for every 5 minutes
    serviceAccountName: vertica-backup
    databasePod: verticadb-sc1-0  # Pod name of the Vertica database
    password: "1234"              # Password for vsql authentication
    archivePrefix: nightly         # Prefix for archive names


verticaRestore:
  enabled: false
  name: vdb-restore
  ignoreClusterLease: "true"
  initPolicy: Revive   # This sets the restore policy
  restorePoint:
    archive: "nightly"   # The archive you created earlier
    index: 1             # The restore point index (update accordingly)
  image: opentext/vertica-k8s:latest  # Vertica image to use
  local:
    requestSize: "10Gi"  # Requested size for local storage
  communal:
    path: "/home/test/vertica/vertica6"  # Communal storage path
  subcluster:
    name: primary         # Subcluster name
    size: 3               # Number of subcluster nodes
  volumes:
    mountPath: "/home/test/vertica/vertica6"  # Mount path for communal storage
    persistentVolumeClaim: verticadb-pvc      # PVC name for communal storage



verticaJob:
  enabled: false
  metadataName: vertica-create-user # Metadata name for the Job resource
  serviceAccountName: vertica-backup # Service account to use for the Job
  
  # Vertica pod details
  podName: verticadb-sc1-0 # Pod name where the VerticaDB instance is running
  
  # Vertica DB admin details
  dbAdminUser: dbadmin # Vertica admin user
  dbAdminPassword: '1234' # Vertica admin user password
  
  # New user creation details
  newUserName: test1 # New user to create in Vertica
  newUserPassword: '12345' # Password for the new user
  
  # Schema privileges for the new user
  schemaName: public # The schema for which privileges are granted
  privileges: "SELECT, INSERT, UPDATE" # Privileges to assign to the new user
