apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertica-backup
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vertica-backup
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources:
    - pods
    - pods/exec
    - services
    - persistentvolumeclaims
  verbs: ["get", "list", "watch", "create", "delete", "exec"]
- apiGroups: ["vertica.com"]  # VerticaDB custom resource
  resources:
    - verticadbs
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["batch"]  # For managing CronJobs and Jobs
  resources:
    - jobs
    - cronjobs
  verbs: ["create", "get", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vertica-pod-exec-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: vertica-backup
  namespace: vertica
roleRef:
  kind: Role
  name: vertica-backup
  apiGroup: rbac.authorization.k8s.io
