apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
{{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
{{- end }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: {{ .Values.persistentVolume.nodeAffinity.operator }}
              values:
{{- range .Values.persistentVolume.nodeAffinity.values }}
                - {{ . }}
{{- end }}
