apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verticadb-pvc
  namespace: vertica
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
