apiVersion: v1
kind: PersistentVolume
metadata:
  name: verticadb-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: {{ .Values.persistentVolume.spec.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/test/vertica/vertica_data/vertica
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node1
                - k8s-node2
