apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes:
{{- range .Values.persistentVolumeClaim.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}
