apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: {{ .Values.verticaDB.metadata.name }}
  namespace: {{ .Values.namespace | default "default" }} # Optional: namespace can be defined in values.yaml or default to "default"
spec:
  subclusters:
{{- range .Values.verticaDB.subclusters }}
    - name: {{ .name }}
      size: {{ .size }}
      serviceType: {{ .serviceType }}
      resources:
        limits:
          cpu: "{{ .resources.limits.cpu }}"
          memory: "{{ .resources.limits.memory }}"
        requests:
          cpu: "{{ .resources.requests.cpu }}"
          memory: "{{ .resources.requests.memory }}"
{{- end }}
  image:
    repository: {{ .Values.verticaDB.image.repository }}
  local:
    requestSize: "{{ .Values.verticaDB.local.requestSize }}"
  communal:
    path: "{{ .Values.verticaDB.communal.path }}"
  volumeMounts:
    - name: communal-storage
      mountPath: "{{ .Values.verticaDB.volumeMounts.communalStorageMountPath }}"
  volumes:
    - name: communal-storage
      persistentVolumeClaim:
        claimName: {{ .Values.verticaDB.volumes.pvcClaimName }}
